#docker-compose up
version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3000:3000'
